spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/walletdb
    username: wallet
    password: walletpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true